### ISSUE TITLE
Prompt customizing

### ISSUE THREAD

**Issue by jovanbulck** [jovanbulck/jsh#3]
Allow a custom prompt. Things todo:
- [x] create new branch
- [x] new `prompt "user defined prompt string"` built_in shell command
- [x] adapting the `char* getprompt(int status)` function in `jsh.c`
  - new definition: `char* getprompt(int status, char *user_prompt_string)`
  - substituting special symbols in user_prompt_string:
    - %u: username
    - %h: hostname
    -  %d: current directory
    - %s: status of last executed command
    - %%: procent sign
- [x] _smart_ truncating the prompt string to a maximum value:
  - e.g. allowing the user to specify a max lenght (eg `%l max_value` ?) for the cur directory and truncating it to min{curdir, max_value} and if truncated -> delete the beginning of the string until the first '/'

Updated todo list:

Todo for release 1.0:
- [x] **testing** + code review (pay even more attention to vulnerabilities as the code processes user input ...) on branch `CustomizingPrompt`
- [x] find a better solution for `MAX_DIR_LENGTH`. This should be user definable, maybe _in_ the prompt string (as in zsh) or using yet another built_in `set` or so? Note the `MAX_PROMPT_LENGTH` can remain hardcoded as we always need a (reasonable) limit for the prompt. When a user tries to set a prompt of more then 100 chars, he's probably hacking :p 

**Todo** for future releases:
- [x] store the user_defined_prompt_string in an environment variable instead of a global variable that is set by a built_in
- [x] user defined coloring for the prompt
- [x] show the username in bold red and/or replace prompt-ending with `#` when sudo is activated
- [ ] themes
- [ ] more options: e.g. the [zsh](http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html) options
- [ ] the pwd expansion code should detect when the home directory substring and replace it with `~`
- [ ] custom prompt things such as `git` support (would be really cool ;-) )
  - [x] show current git branch
  - [ ] show whether things have changed since last commit
- [ ] the feature-to-undo-all-other-feature-requests is probably to allow the output of any shell command to be included in the prompt.
- [ ]  cutting off the path until a user-defined level (e.g. lowest) directory
- [ ] update the man page to document the options for the prompt command
